### ISSUE TITLE
debugging a remote app ?

### ISSUE THREAD

**Issue by joeblew99** [aarzilli/gdlv#10]
Wondering if this is supported with GDLV and Delve ?

Say i have a golang process running on linux box that has a static IP, and i want to debug it from my Desktop that is at home (and behind NAT).  

Secondly, if i have 2 golang processes on that linux box, can i debug each golang process separately ?

**Comment by aarzilli** [comment]
See `gdlv connect` and the `--headless` option of delve.

**Comment by joeblew99** [comment]
Thankyou
