### ISSUE TITLE
How to debug a test?

### ISSUE THREAD

**Issue by jeremyjjbrown** [aarzilli/gdlv#13]
in dlv it's simple. I can just:
```
$ dlv test ./control
(dlv) break control.TestDockerGetsRepos
(dlv) continue
```

from the root of my project where there is a go test:
`./control/docker_test.go`

with a test function:
`func (suite *DockerSuite) TestDockerGetsRepos() {...}`

If I do gdlv test ./control I get:
```
Compiling...done
can't load package: package gerrit.it.here.com/olp/dp/ipaas: no buildable Go source files in /Users/jeremybr/Dev/src/gerrit.it.here.com/olp/dp/ipaas

exit status 1
```

**Comment by aarzilli** [comment]
```
cd control
gdlv test
```

**Comment by jeremyjjbrown** [comment]
Excellent! Thanks. Couldn't be easier.

**Comment by jeremyjjbrown** [comment]
BTW, this project is awesome. Thanks!

**Comment by aarzilli** [comment]
Thank you!
