### ISSUE TITLE
How to pass command line arguments to the program which is being debugged?

### ISSUE THREAD

**Issue by naqvijafar91** [aarzilli/gdlv#15]
With delve, you can pass arguments like this:

`dlv debug -- --datadir /Users/jafarnaqvi/blockchain/test`

but if use

`gdlv debug -- --datadir /Users/jafarnaqvi/blockchain/test`

It does not work

**Comment by aarzilli** [comment]
gdlv parses the command line differently compared to dlv, since it doesn't have any options of its own everything after the verb will be forwarded to the program:

```
gdlv debug --datadir /Users/jafarnaqvi/blockchain/test
```
