### ISSUE TITLE
 x11driver: no matching Visualid

### ISSUE THREAD

**Issue by nuliknol** [aarzilli/gdlv#16]
I  wonder what could be the cause of this error?
```
niko@desk:/home/xxxx/src$ gdlv debug github.com/project/repo -- -option1 0 --port 5500
could not create window: x11driver: no matching Visualidn
```
 I am using Xinerama over 2 Nvidia GPUs with 3 monitors and i3 window manager, on Ubuntu 16.04, if this matters.

**Comment by aarzilli** [comment]
can you post the output of `xdpyinfo`?

**Comment by aarzilli** [comment]
Closing, no feedback.
