### ISSUE TITLE
How to configure substitute-path?

### ISSUE THREAD

**Issue by laujinkai** [aarzilli/gdlv#19]
Is configuration for substitute-path supported in gdlv?

**Comment by aarzilli** [comment]
No, it was never ported over.

**Comment by rainbow-bash** [comment]
is there any plans on implementing it? im using gdlv to debug my backend and recently put it inside a docker container so i lowkey need it :s

EDIT:

nevermind just checked the config command and there it is :D thanks
<img width="727" height="441" alt="Image" src="https://github.com/user-attachments/assets/08c5e0a4-dde7-41e7-8be9-e2099b67eae6" />
