### ISSUE TITLE
How do you actually run it?

### ISSUE THREAD

**Issue by wdevore** [aarzilli/gdlv#20]
I ran the "go get.." and tried "go install -i ." but I can't figure out how to run gdlv on OSX.

**Comment by Nzen** [comment]
I've not yet gotten gdlv to recognize the dlv session. Nonetheless, it looks like we're assumed to be aware of using dlv as a debugging server. We start it on a known port and then have gdlv listen to that port:
`dlv --headless --log --listen localhost:40000 debug [[ your package, ex main ]] `
And then, in a separate terminal, launch gdlv
`gdlv connect localhost:40000`
gdlv doesn't find the function context, but hopefully this helps someone else figure out the right setup.
