### ISSUE TITLE
Allow users to change default font

### ISSUE THREAD

**Issue by sunnyregion** [aarzilli/gdlv#21]
OS:ubuntu
golang:v1.10.2

gdlv can't show chinese code. 
How to debug it?
Thx a lot!

**Comment by sunnyregion** [comment]
![2018-05-30 09-46-11](https://user-images.githubusercontent.com/19296528/41215139-804a4c74-6d81-11e8-9839-89fdce6a5eb6.png)

**Comment by sunnyregion** [comment]
![2018-06-11 14-12-10](https://user-images.githubusercontent.com/19296528/41215167-9957e032-6d81-11e8-9e5c-9bd77bf48c86.png)

**Comment by aarzilli** [comment]
I'm using Droid Sans Mono, which doesn't seem to cover have coverage for Chinese characters. There isn't an easy way to replace it at the moment, short of replacing the ttf file in vendor/github.com/aarzilli/nucular/DroidSansMono.ttf, running go generate there and recompiling.

**Comment by sunnyregion** [comment]
I do it。But not work

**Comment by sunnyregion** [comment]
sorry，I user that is gdlv ，not nucular

**Comment by sunnyregion** [comment]
//go:generate go-bindata -o internal/assets/assets.go -pkg assets fontawesome-webfont.ttf
go generate
 running "go-bindata": exec: "go-bindata": executable file not found in $PATH

**Comment by sunnyregion** [comment]
Thx a lot .I get it.
1)sudo apt install go-bindata
2) replacing the ttf file in vendor/github.com/aarzilli/nucular/DroidSansMono.ttf
3)go generate
  go build
  go install

**Comment by aarzilli** [comment]
Reopening because there should be an easier way to fix this.
