### ISSUE TITLE
gdlv debugs optimized function

### ISSUE THREAD

**Issue by ianrtaylor** [aarzilli/gdlv#25]
When I attempt to debug a simple main.go file using `gdlv debug main.go`, I get the warning "Warning: debugging optimized function $GOROOT/src/runtime/proc.go", and I can't debug my un-optimized main.go file.  

I've attempted building the file with optimizations and inlining turned off (using the suggestions in https://groups.google.com/forum/#!topic/golang-nuts/MASPs81edfU), but that hasn't helped. I don't have this problem when I debug with the delve backend, but I'd really like to use the visual debugger.  

Here's what I'm seeing:
<img width="737" alt="screen shot 2019-01-22 at 9 42 04 am" src="https://user-images.githubusercontent.com/41970908/51543826-79a8a300-1e2c-11e9-91e1-027f4d43c1cc.png">

I'm using go version `go1.11.4 darwin/amd64` and running gdlv on macOS 10.13.6.

**Comment by aarzilli** [comment]
You just have to do the same thing you do with delve: set a breakpoint on `main.main` and `continue`.
