### ISSUE TITLE
Support you

### ISSUE THREAD

**Issue by whereswaldon** [aarzilli/gdlv#28]
I can't even express how much value this project has added to my development cycle since I found it a week ago. Thank you so much for building it!

Do you have anywhere I can donate to support this project? Or is there some non-monetary way I can support it?

**Comment by aarzilli** [comment]
If you want you can send me an amazon gift card or money through paypal at my email address (alessandro.arzilli@gmail.com). The non-monetary way to contribute is obivously code contributions, the two things that I would be most happy to see are:
1. A change to macOS debugserver to allow SIGSEGV to pass through to the target program (see https://github.com/go-delve/delve/issues/1371#issuecomment-429555169)
2. A port of shiny to the metal API on macOS, it currently uses OpenGL on macOS but it's deprecated and I worry that in the future it will be removed.

**Comment by aarzilli** [comment]
PS. glad to hear that gdlv is useful to you.

**Comment by whereswaldon** [comment]
I don't use a mac, so I'm afraid I'm not likely to be able to help in those two areas. Look out for a gift card!

**Comment by aarzilli** [comment]
Thank you!

**Comment by zchee** [comment]
@aarzilli hi,

 > A port of shiny to the metal API on macOS, it currently uses OpenGL on macOS but it's deprecated and I worry that in the future it will be removed.

exp/shiny started supporting Metal.
looking forward it :)

> shiny/driver/mtldriver: add start of a Metal API-based driver
https://github.com/golang/exp/commit/81c71964d733d2e3e2375a315c0e2fd4d162adc4

**Comment by aarzilli** [comment]
@zchee I've updated shiny to the latest version.

**Comment by zchee** [comment]
@aarzilli great!

I'v tried to using `metal`, seems to have problem that font size is too small than non `metal` build.
I don't know yet wrong font size problem which gdlv or shiny, but almost works fine expect the above problem. thanks develop!

**Comment by aarzilli** [comment]
The font is software rendered independently from the backend so it shouldn't make any different unless the opengl backend was somehow triggering macOS into doing some automatic upscaling. But there's nothing I can do about that.
