### ISSUE TITLE
step/next key bindings could be more intuitive

### ISSUE THREAD

**Issue by rogpeppe** [aarzilli/gdlv#29]
Firstly, thanks for making this GUI - it's really great!

I just had a minor thought about the key bindings for stepping.

I think I understand the current logic: it's as if instructions are laid out left to right and the stack goes down and up.

However in the GUI context, when stepping and looking at the source, I think a more natural view is to see the source lines as up and down, the way they're laid out on the screen and stepping into and out of a function as right and left respectively (as if stepping into a function is jumping into a new tab to the right of the current one).

This view would suggest the following bindings:

    Alt-down: next
    Alt-right: step
    Alt-left: step out

**Comment by aarzilli** [comment]
If you look at debugger icons on both eclipse and VSCode having a arrow pointing right for next is a well established metaphor, same goes for an arrow pointing down for step into and up for step out. If I ever get icons for the command buttons it would have to match that so I think these bindings are better.

**Comment by rogpeppe** [comment]
OK, that's a good reason. I've just tweaked my local version. :)
