### ISSUE TITLE
using an old version of delve gives "Loading..." window

### ISSUE THREAD

**Issue by rogpeppe** [aarzilli/gdlv#31]
In issue #30, I discovered that if you use gdlv with an old version of delve, it fails by showing a stacktrace window that always displays "Loading...".

It would be better if a more obvious error was displayed, such as "old version of delve in use", or even better, if it could fall gracefully back to using the old version of the API.

**Comment by aarzilli** [comment]
Needs https://github.com/go-delve/delve/pull/1571 to be fixed.

**Comment by aarzilli** [comment]
Fixed. Thanks for all the QA :smile:
