### ISSUE TITLE
Installation errors due to dependency problems

### ISSUE THREAD

**Issue by Bios-Marcel** [aarzilli/gdlv#38]
I was following the readme and got this after running `go get -u github.com/aarzilli/gdlv`:

```
go: finding github.com/derekparker/delve v1.2.0
go: github.com/derekparker/delve@v1.2.0: parsing go.mod: unexpected module path "github.com/go-delve/delve"
go get: error loading module requirements
```

**Comment by aarzilli** [comment]
I'm not sure why it's trying to import version v1.2.0, for you, when the minimum version I was specifying was 1.1.0 so I can't actually reproduce this problem, but it should be fixed now.
