### ISSUE TITLE
Ctrl-plus and Ctrl-minus don't appear to work on MacOS Mojave

### ISSUE THREAD

**Issue by jpapejr** [aarzilli/gdlv#39]
Per the subject, I see no effect when trying to scale up the font size in the window. 

MacOS 10.14.6 Mojave

**Comment by aarzilli** [comment]
I don't have any way to test MacOS 10.14 so you'll have to add a `fmt.Printf("%#v\n", e)` before https://github.com/aarzilli/gdlv/blob/master/main.go#L196 and see what happens when you press ctrl+/-

**Comment by myroslavrys** [comment]
> Per the subject, I see no effect when trying to scale up the font size in the window.
> 
> MacOS 10.14.6 Mojave

Same story.
Default font size incredible small for Retina display. Is any configuration available for default configuration?

**Comment by myroslavrys** [comment]
Ok.
Added fmt.Printf("%#v\n", e) just like you mentioned.

macOS Mojave 10.14.6v2

CTRL-PLUS
key.Event{Rune:-1, Code:0xe0, Modifiers:0x2, Direction:0xa}
key.Event{Rune:61, Code:0x2e, Modifiers:0x2, Direction:0x1}
key.Event{Rune:-1, Code:0xe0, Modifiers:0x0, Direction:0xb}

CTRL-SHIFT-PLUS
key.Event{Rune:-1, Code:0xe1, Modifiers:0x1, Direction:0xa}
key.Event{Rune:-1, Code:0xe0, Modifiers:0x3, Direction:0xa}
key.Event{Rune:61, Code:0x2e, Modifiers:0x3, Direction:0x1}
key.Event{Rune:-1, Code:0xe0, Modifiers:0x1, Direction:0xb}
key.Event{Rune:-1, Code:0xe1, Modifiers:0x0, Direction:0xb}

CTRL-MINUS
key.Event{Rune:-1, Code:0xe0, Modifiers:0x2, Direction:0xa}
key.Event{Rune:31, Code:0x2d, Modifiers:0x2, Direction:0x1}
key.Event{Rune:-1, Code:0xe0, Modifiers:0x0, Direction:0xb}

CTRL-SHIFT-MINUS
key.Event{Rune:-1, Code:0xe1, Modifiers:0x1, Direction:0xa}
key.Event{Rune:-1, Code:0xe0, Modifiers:0x3, Direction:0xa}
key.Event{Rune:31, Code:0x2d, Modifiers:0x3, Direction:0x1}
key.Event{Rune:-1, Code:0xe1, Modifiers:0x2, Direction:0xb}
key.Event{Rune:-1, Code:0xe0, Modifiers:0x0, Direction:0xb}

**Comment by aarzilli** [comment]
Fixed 71073e779b949535482349b0100baabd0ca26ebf
