### ISSUE TITLE
TestShortenType is breaking the tests

### ISSUE THREAD

**Issue by wesleyParriott** [aarzilli/gdlv#44]
When I run the command `$ go test -v` I receive this error message: 
`github.com/aarzilli/gdlv [github.com/aarzilli/gdlv.test]
./misc_test.go:9:10: undefined: shortenType
FAIL    github.com/aarzilli/gdlv [build failed]`

Obviously it's complaining about the shortenType function which looks like it's replaced by prettyprint.ShortType(type.V).  I came to conclusion by just grepping for all the instances of shortenType in the code base. 

Here's all the instances in the shortenType in the code base
`$ grep -inr shortenType *
infovars.go:75: r.ShortType = prettyprint.ShortenType(v.Type)
internal/prettyprint/prettyprint.go:408:        return ShortenType(v.Type)
internal/prettyprint/prettyprint.go:411:func ShortenType(typ string) string {
internal/prettyprint/prettyprint.go:412:        out, ok := shortenTypeEx(typ)
internal/prettyprint/prettyprint.go:419:func shortenTypeEx(typ string) (string, bool) {
internal/prettyprint/prettyprint.go:422:                sub, ok := shortenTypeEx(typ[2:])
internal/prettyprint/prettyprint.go:425:                sub, ok := shortenTypeEx(typ[1:])
internal/prettyprint/prettyprint.go:436:                                        key, keyok := shortenTypeEx(typ[4:i])
internal/prettyprint/prettyprint.go:437:                                        val, valok := shortenTypeEx(typ[i+1:])
misc_test.go:7:func TestShortenType(t *testing.T) {
misc_test.go:9:         out := shortenType(src)`

My suggestion is to remove TestShortenType out of misc_tests.go which I did in pull request #43

**Comment by aarzilli** [comment]
Thank you.
