### ISSUE TITLE
Ctrl-plus and Ctrl-minus don't appear to work on macOS Catalina

### ISSUE THREAD

**Issue by leighmcculloch** [aarzilli/gdlv#46]
Similar to #39 opening gdlv on macOS Catalina doesn't respond to keypresses of Ctrl-minus and Ctrl-minus.

I'm attempting to use those keys to scale the app/fonts because on a Mac retina screen it opens looking tiny.

I added a `fmt.Printf` as is described in https://github.com/aarzilli/gdlv/issues/39#issuecomment-534694736, and the result was curious. Most key presses in the app result in no output. The only key that when I press causes output is the Enter/Return key. When pressing Enter/Return, I see:
```
key.Event{Rune:10, Code:0x28, Modifiers:0x0, Direction:0x1}
```

**Comment by aarzilli** [comment]
This sounds more like "keyboard input doesn't work at all" than "Ctrl-plus and Ctrl-minus". If the rest of the keyboard worked you could select the command line and type `config zoom 2.0` and it would work...

You could try one of the examples in [nucular](github.com/aarzilli/nucular), for example [simple](https://github.com/aarzilli/nucular/blob/master/_examples/simple/main.go), adding `fmt.Printf("%#v\n", ei)` to [handleEventLocked](https://github.com/aarzilli/nucular/blob/master/shiny.go#L109).

This will print all events that nucular receives from shiny so we can figure out if I'm dropping the keyboard events, or shiny isn't generating them. Is this with metal or opengl?
