### ISSUE TITLE
question about remote debugging

### ISSUE THREAD

**Issue by shawn-xdji** [aarzilli/gdlv#47]
Hi Arzilli,

I tried to run gdlv on windows to debug a session on remote linux server, is it supposed to work?
I could launch it successfully while the 'listing' window shows assembly only.

steps:

linux server: dlv debug --headless --listen <addr>
windows:     gdlv connect <addr>

Thanks a  lot.

**Comment by aarzilli** [comment]
You need to tell it where the source code is through the config command (the path subsitution rules).
