### ISSUE TITLE
Gdlv only lists a subset of the goroutines

### ISSUE THREAD

**Issue by jbeshay** [aarzilli/gdlv#49]
I am trying to use gdlv to debug a core dump with almost 1k goroutines. When I do that in dlv, I get a list of all goroutines:
```
[947 goroutines]
(dlv)
```
However, gdlv UI only shows a hundred or so. Even if I try to increase the limit in the goroutines window, the list doesn't grow. Am I missing something here?

**Comment by aarzilli** [comment]
Changes to the configuration only applied after a continue operation (continue, next, step, etc). Fixed it. Thank you.

**Comment by jbeshay** [comment]
Thanks @aarzilli!
