### ISSUE TITLE
Can not launch gdlv in remote x11 server

### ISSUE THREAD

**Issue by lday0321** [aarzilli/gdlv#5]
When I use gdlv on the local server, everything is ok. However, when i try to launch gdlv on my remote x11 server(by using xmanager), I got such error message: "could not create window: x11driver: shm.Init failed: No extension named MIT-SHM could be found on on the server",  could i disable MIT-SHM?

**Comment by aarzilli** [comment]
Unfortunately shiny does not work with remote servers, see: https://github.com/golang/go/issues/15100

**Comment by lday0321** [comment]
Hope gdlv can support remote server
