### ISSUE TITLE
Make possible saving layouts

### ISSUE THREAD

**Issue by gustavo-hms** [aarzilli/gdlv#50]
Hi!

First of all, thanks for the project.

I'd like to ask you to make possible to save panels layouts. Currently, every time I open `gdlv`, it displays the `Listing`, `Command`, `Stacktrace` and `Variables` panels, and I always find myself adding `Breakpoints` and `Sources`. It's tedious and time consuming to do this setup again and again. So, if there was an option to save the current layout (or even save it automatically like `gdlv` does with breakpoints) for them to be restored the next time I run `gdlv`, it would come in handy.

**Comment by aarzilli** [comment]
You can already save a layout using the layout command:
```
layout save mylayout layout description goes here
```

will save the current layout as `mylayout`

```
layout mylayout
```

will restore it. Use `default` as the layout name to change the default layout.

**Comment by gustavo-hms** [comment]
I didn't realise I can do that. Thanks for the explanation.

Anyway, I see now that reading the output of the `help` command it's possible to discover this functionality, even though I didn't. Perhaps it was a lack of attention on my side, perhaps a usability problem, but in any case it's not evident that, to get our layout loaded at startup, we can overwrite the `default` layout. So, if `help` could be more explicit at how  we can make a custom layout the default, I think it could already help.

**Comment by aarzilli** [comment]
Added to documentation in d4d99011ec73395cd5b71757f2494c6af74a9b6b.

**Comment by tmelot2** [comment]
This doesn't work for me across gdlv sessions. I can create a layout, save it, & see it in the list. But when I close that session & open another one, the layout is gone.
