### ISSUE TITLE
Puzzling differences between `gdlv run` and `gdlv debug` output.

### ISSUE THREAD

**Issue by carlca** [aarzilli/gdlv#54]
Hi Alessandro, firstly can I say thank you for producing this software. In my struggles to find a good solution for producing Golang I have been tried every combination of tools. For instance Atom is a fine editor, but currently the Go-Debug add-on does not work! VSCode on the other hand is a reasonable editor, but the linkup with Delve is horribly slow and the watch values are not even shown in hexadecimal! Now, I am using https://www.chimehq.com as my editor - it's small and fast, and I'm hoping to use `gdlv` as my debugger.

However, I'm trying to debug the code at https://github.com/carlca/gowig. If I run `gdlv` with `gdlv run main.go Diffusion,bwpreset` the value `size` is correctly printed with the value 7. If I use `gdlv debug main.go Diffusion.bwpreset` the value `size` is shown on screen as having the value `1025535859`. Instinctively I feel that something may not be quite right here ;-) Maybe, having just started using `gdlv`, I'm doing something wrong. What do you think?

Cheers,
Carl

**Comment by carlca** [comment]
As I suspected, I was doing something wrong! When I tried to run `gdlv debug main.go Diffusion.bwpreset`, it was interpreting `main.go` as a program parameter! If I just run `gdlv debug Diffusion.bwpreset` everything works perfectly.

Am I right in thinking that when I come to debug a new piece of code, I should first run `gdlv run main.go Diffusion.bwpreset` to attach the debugger to the process, and then subsequently run `gdlv debug Diffusion.bwpreset` for each debugging run.

**Comment by carlca** [comment]
Obviously, `Diffusion.bwpreset` is just the parameter associated with this particular task ;-)

**Comment by aarzilli** [comment]
`gdlv run x.go ...` compiles `x.go` and then passes everything else as an argument, `gdlv debug ...` compiles whatever is in the current directory and passes everything as argument. You don't have to use `run` the first time and it won't work at all unless the entire program is self contained in a single go file.

**Comment by carlca** [comment]
Ah! Understood. Thanks again for producing this excellent tool. I will do my best to recommend it, where appropriate of course, on Twitter 😉

**Comment by aarzilli** [comment]
You're welcome.
