### ISSUE TITLE
Method to pass arguments to dlv

### ISSUE THREAD

**Issue by r00tu53r** [aarzilli/gdlv#55]
Is there a way to pass dlv arguments from gdlv ? I am trying to set the working directory (dlv cmdline arg `--wd`) from gdlv. I am unable to find a way.

**Comment by aarzilli** [comment]
There is no way to pass arguments to dlv. Directories work the opposite way in gdlv: start gdlv in the working directory you want, specify the main module directory with `-d` before the command `gdlv -d /path/to/main/module debug program arguments...`
