### ISSUE TITLE
gdlv exec error: no sRGB texture formats found

### ISSUE THREAD

**Issue by phil-s1** [aarzilli/gdlv#56]
gdlv version 1.7
dlv version 1.7.2
go version 1.17.1 darwin/amd64
macOS 11.6, build; 20G165

Running 

`
dlv exec path/to/bin
`

returns immediate error:

`
error: no sRGB texture found
`

Anybody know the cause/fix for this?

**Comment by aarzilli** [comment]
I don't have a mac where this happens, you will have to investigate it yourself.

**Comment by phil-s1** [comment]
Test on a different install with go 1.16.5 no problem.
Another difference btw the two tests is the one that produces the error is a VM.
Will document further results as and when.

**Comment by aarzilli** [comment]
If it's a VM it's possible that it simply does not support opengl.

**Comment by phil-s1** [comment]
Bingo! Per Parallels Desktop docs:

"As of today, it is technically not possible to implement OpenGL support in macOS (Linux) virtual machines."

Thanks for the hint! I guess we can close this issue.
