### ISSUE TITLE
pass window arguments to window system, or remember window size/placement

### ISSUE THREAD

**Issue by jlearman** [aarzilli/gdlv#57]
gdlv is fantastic, many thanks!  But, because no good deed goes unpunished:

Each time I start gdlv, it opens in a small window that I have to resize.  I'm using X, and I'd be happy to pass a -geometry parameter.  Better yet, gdlv could remember how big it was when it was last quit.

**Comment by aarzilli** [comment]
Resize the window, then `layout save default`

**Comment by jlearman** [comment]
Thanks, didn't see that!
