### ISSUE TITLE
Document Shortcuts

### ISSUE THREAD

**Issue by renannprado** [aarzilli/gdlv#6]
I was about to create an issue to tell to increase the font size just like #4 and found that there's a shortcut for it.
It would be nice if all the shortcuts (if there are more) were documented.

**Comment by aarzilli** [comment]
I'll change README to mention Ctrl+plus/minus, the other shortcuts are already documented in the output of `help` (there aren't many).

**Comment by renannprado** [comment]
@aarzilli are you sure that the other shortcuts are documented in the output of `help`?
this what I see when I see the usage of the CLI:
```usage:
	gdlv connect <address>
	gdlv debug <program's arguments...>
	gdlv run <program file> <program's arguments...>
	gdlv exec <executable> <program's arguments...>
	gdlv test <testflags...>
	gdlv attach <pid> [path to executable]```

**Comment by aarzilli** [comment]
help inside the application, not that help.

**Comment by renannprado** [comment]
Oh... I see... thanks!
