### ISSUE TITLE
is a light theme possible?

### ISSUE THREAD

**Issue by mark-summerfield** [aarzilli/gdlv#67]
I find the dark theme unreadable. It is possible to set a light theme?

**Comment by aarzilli** [comment]
`config` the first thing is a theme selector.

**Comment by mark-summerfield** [comment]
But that's only useful if you tell me what the valid theme names are. I tried "light" and it had no effect.

**Comment by aarzilli** [comment]
config will open a window, the first line of the window has a drop down menu with a list of themes.

**Comment by mark-summerfield** [comment]
I don't have a drop down menu, here's a screenshot when I run `gdlv debug` in a folder with a .go application:
![Screenshot_2023-03-25_16-40-59](https://user-images.githubusercontent.com/1773348/227730369-c8f03fe5-f427-46ba-804d-75acc8c91fa2.png)
I clicked the New Window menu but that doesn't list a config window option.

**Comment by aarzilli** [comment]
Use the config command. Press esc, type "config" and then press enter.

**Comment by mark-summerfield** [comment]
Thank you, that worked.
