### ISSUE TITLE
gdlv install not installing

### ISSUE THREAD

**Issue by devmaha** [aarzilli/gdlv#69]
Thanks for open sourcing this library.
I and my team tried tried installing it on Linux - followed all the steps - but gdlv is no where to be found. There is no message printed at 'install' step, it just finishes.
Any guidance is appreciated. 

Thanks

**Comment by aarzilli** [comment]
From `go help install`:

```
Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set.
```

**Comment by devmaha** [comment]
That was it, somehow missed to check in one of those directories. Many thanks
