### ISSUE TITLE
error: unknown flag --backend

### ISSUE THREAD

**Issue by gonzaloserrano** [aarzilli/gdlv#7]
Hi,

Since I haven't been able to debug or c&p the error from the UI, here you are an screenshot.

With `$ gdlv debug`:

![screenshot 2017-05-09 17 36 26](https://cloud.githubusercontent.com/assets/349328/25859193/114e65a8-34de-11e7-9544-1f998165182d.png)

Regards,

**Comment by aarzilli** [comment]
Update delve.
