### ISSUE TITLE
Help missmatch on gdlv and dlv

### ISSUE THREAD

**Issue by George-Spanos** [aarzilli/gdlv#76]
First of all thanks for this amazing project!

I just started using gdlv today and noticed that the gdlv help command does not have an options to list breakpoints. I can normally clear breakpoints via the ui, but when I try to `clearall` for example I get that the `Command failed: command "clearall" not available` which is expected as it's not listed under help.
![Screenshot_20231208_124215](https://github.com/aarzilli/gdlv/assets/27289923/8649ccad-6397-43bf-b5fe-5946f03cd95c)

Wheareas when I just use the dlv command on my computer on the same project with the same arguments I get all the list of commands shown on dlv documentation
![Screenshot_20231208_124338](https://github.com/aarzilli/gdlv/assets/27289923/931e9a8e-3b08-4876-85cb-47982bbcb5ac)
In vanilla delve all commands work as expected.

Any ideas?

**Comment by aarzilli** [comment]
You can get a list of all breakpoints by opening the breakpoints window and you can clear all breakpoints by right clicking on a breakpoint and selectin "Clear All"

**Comment by George-Spanos** [comment]
So it's expected that I cannot clear them by the bottom left window? I would prefer to clear them via console. It's not an "issue" so to say, I just wanted to make sure this is expected.

**Comment by aarzilli** [comment]
Yes, not all the commands of dlv are replicated in gdlv.

**Comment by George-Spanos** [comment]
Thank you, I'm gonna close this.
