### ISSUE TITLE
What trying to run a test I get Error refreshing state Open(): open _testmain.go: no such file or directory

### ISSUE THREAD

**Issue by TheLazyLemur** [aarzilli/gdlv#77]
When I run gdlv test I get this issue:

```
Error refreshing state Open(): open _testmain.go: no such file or directory
```

**Comment by aarzilli** [comment]
That's normal. When you run tests the main function is autogenerated by the toolchain and the corresponding source file is deleted once compilation is finished.

**Comment by TheLazyLemur** [comment]
I am a little confused, how do I add a breakpoint on a test then? Thank you for the quick response

**Comment by aarzilli** [comment]
Either open the functions window and set a breakpoint on a function, or use the sources window to switch to a source file and set a breakpoint on a line, or use the `break` command.
