### ISSUE TITLE
Can not connect to display server

### ISSUE THREAD

**Issue by rakyll** [aarzilli/gdlv#8]
`gdlv core <executable> <core>` panics immediately upon start with an "empty display string" panic:

```
gdlv core ./hello core
panic: empty display string

goroutine 1 [running]:
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/clipboard.Start()
	/usr/local/google/home/jbd/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/clipboard/clipboard_linux.go:26 +0x7e
github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular.NewMasterWindow(0x80, 0x98dbfa, 0x4, 0x9ae7b8, 0x0, 0x0)
	/usr/local/google/home/jbd/src/github.com/aarzilli/gdlv/vendor/github.com/aarzilli/nucular/shiny.go:91 +0x197
main.main()
	/usr/local/google/home/jbd/src/github.com/aarzilli/gdlv/main.go:675 +0xd5
```

**Comment by aarzilli** [comment]
This doesn't have anything to do with core files. How are you running this, it can't connect to X11.

**Comment by rakyll** [comment]
Correct, gdlv panics regardless of the subcommand due to the missing desktop environment. I am not sure if you can do anything to detect the case that desktop env is missing and die with a friendlier error. Closing this issue.

**Comment by aarzilli** [comment]
Yes, a friendlier error message would be appropriate.
