### ISSUE TITLE
Osx maximise window results in beach all forever

### ISSUE THREAD

**Issue by joeblew99** [aarzilli/gdlv#9]
Go 1.8.3
Osx, latest public stable.

When I maximise the window it goes into beachball lockup for ever.
When I minimise down to the dock, and then click on it in the dock it also goes into beachball forever.

When the window is in normal mode, resizing the window works perfectly btw. It's very fast too.

I also tried https://github.com/aarzilli/nucular to see if the same behaviour exists there and it does.

**Comment by aarzilli** [comment]
See if this works.

**Comment by joeblew99** [comment]
@aarzilli 
I tried it out for Maximising and minimising.
All works perfectly on OSX now.

Really awesome & thank you !
